"""add about_intro_en for bilingual about page description

Revision ID: 16bde59ce22f
Revises: aee291c6966c
Create Date: 2026-08-16 23:04:10.502405

為什麼需要這個欄位：
  site_settings 的敘述型欄位中，只有 about_intro 沒有 *_en 版本。
  少了它，/about 的英文 meta description 會回退到站台預設，
  結果與首頁的描述一模一樣 —— 違反 SAI §12.1「每頁 description
  不重複」。about.html 的 localized(settings, 'about_intro') 早已
  預期這個欄位存在，補上後不需要改任何模板。

  about_methods_zh 同樣缺英文版，但它不參與 description 的組成，
  因此不在本次範圍；要補時比照此 migration 即可。

安全性：nullable 欄位，既有資料列不受影響，downgrade 可還原。
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bde59ce22f'
down_revision = 'aee291c6966c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_intro_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('about_intro_en')

    # ### end Alembic commands ###
