# ============================================================
# NTUST SiPh Lab - Migration：equipment 資料表
#
# 上下游：
#   flask db upgrade -> migrations/env.py -> 本檔 upgrade()
#       -> 新增 equipment 表
#       -> repositories/equipment.py 查詢
#       -> /equipment 公開頁依 ownership 分組顯示
#   前一版：16bde59ce22f（about_intro_en）
#
# 檔案路徑：
#   migrations/versions/6018c76001f9_add_equipment_table.py
#
# 建立日期：2026-09-09 / 版本：v1.0
#
# 功能說明：
#   新增設備／可用研究設施資料表，支援前台 /equipment 頁面。
#   純結構變更，不寫入任何資料 —— 內容由 seed 腳本以 draft 匯入
#   或由管理者於後台建立。
#
# 這是本專案第一個「新增資料表」的 migration：
#   前兩次部署（PR #2、#3）都是零 schema 變更，因此可以只切流量、
#   無條件回滾。這次不行 —— 部署時必須執行 flask db upgrade，
#   回滾則需要先 downgrade。downgrade() 會 DROP TABLE equipment，
#   表內資料一併消失，回滾前務必確認該表沒有需要保留的內容。
#
# 主要責任：
#   1. upgrade()：建立 equipment 表、三個 CheckConstraint、三個索引。
#   2. downgrade()：移除索引與整張表。
#
# 為什麼時間欄位寫 sa.DateTime(timezone=True) 而不是 UtcDateTime：
#   Alembic autogenerate 產生的是 app.models.mixins.UtcDateTime，
#   但 migration 檔沒有 import app —— 直接執行會 NameError。
#   而 UtcDateTime 的 impl 就是 DateTime(timezone=True)，底層 DDL
#   完全相同（見 mixins.py 該類別說明），因此改寫為原生型別。
#   這也讓 migration 不相依於應用程式碼：日後 UtcDateTime 若改名
#   或移除，這份歷史紀錄仍然可以重放。既有的 initial schema
#   migration 也是這樣寫的。
#
# 維護契約：
#   category / ownership / publish_status 的允許值同時存在於
#   app/models/mixins.py 的常數與此處的 CheckConstraint。
#   新增值時兩邊都要改，否則會出現「後台可選但 DB 拒絕」。
#
# 驗證方式：
#   pytest tests/test_equipment.py tests/test_schema.py
#   flask db upgrade && flask db downgrade && flask db upgrade
# ============================================================
"""add equipment table

Revision ID: 6018c76001f9
Revises: 16bde59ce22f
Create Date: 2026-09-09 11:00:30.828919

安全性：新增獨立資料表，不觸及既有資料列。
downgrade 會刪除整張表，非可逆操作（表內資料會遺失）。
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6018c76001f9'
down_revision = '16bde59ce22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name_zh', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('model_number', sa.String(length=160), nullable=True),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('ownership', sa.String(length=30), nullable=False),
    sa.Column('description_zh', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('specs_zh', sa.Text(), nullable=True),
    sa.Column('specs_en', sa.Text(), nullable=True),
    sa.Column('location_zh', sa.String(length=255), nullable=True),
    sa.Column('location_en', sa.String(length=255), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('photo_alt_zh', sa.String(length=220), nullable=True),
    sa.Column('photo_alt_en', sa.String(length=220), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('publish_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('measurement', 'packaging', 'inspection', 'source', 'computing', 'component', 'other')", name='ck_equipment_category'),
    sa.CheckConstraint("ownership IN ('lab', 'institute', 'shared')", name='ck_equipment_ownership'),
    sa.CheckConstraint("publish_status IN ('draft', 'published', 'archived')", name='ck_equipment_publish_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index('ix_equipment_publish_ownership', ['publish_status', 'ownership', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_publish_status'), ['publish_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_slug'))
        batch_op.drop_index(batch_op.f('ix_equipment_publish_status'))
        batch_op.drop_index('ix_equipment_publish_ownership')

    op.drop_table('equipment')
    # ### end Alembic commands ###
