"""initial schema: 7 core tables per SAI section 8

Revision ID: aee291c6966c
Revises: 
Create Date: 2026-08-15 12:37:02.669409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee291c6966c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('name_zh', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=True),
    sa.Column('degree', sa.String(length=80), nullable=True),
    sa.Column('title_zh', sa.String(length=120), nullable=True),
    sa.Column('title_en', sa.String(length=160), nullable=True),
    sa.Column('education_zh', sa.Text(), nullable=True),
    sa.Column('education_en', sa.Text(), nullable=True),
    sa.Column('entry_year', sa.Integer(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('research_focus_zh', sa.Text(), nullable=True),
    sa.Column('research_focus_en', sa.Text(), nullable=True),
    sa.Column('thesis_title_zh', sa.Text(), nullable=True),
    sa.Column('thesis_title_en', sa.Text(), nullable=True),
    sa.Column('skills_json', sa.Text(), nullable=True),
    sa.Column('bio_zh', sa.Text(), nullable=True),
    sa.Column('bio_en', sa.Text(), nullable=True),
    sa.Column('current_affiliation', sa.String(length=200), nullable=True),
    sa.Column('current_position', sa.String(length=160), nullable=True),
    sa.Column('destination_public', sa.Boolean(), nullable=False),
    sa.Column('email_public', sa.String(length=200), nullable=True),
    sa.Column('orcid_url', sa.String(length=255), nullable=True),
    sa.Column('scholar_url', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('external_url_label', sa.String(length=120), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('photo_alt_zh', sa.String(length=200), nullable=True),
    sa.Column('photo_alt_en', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('publish_status', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('seo_title_zh', sa.String(length=180), nullable=True),
    sa.Column('seo_description_zh', sa.String(length=320), nullable=True),
    sa.Column('legacy_pending_detail', sa.Boolean(), nullable=False),
    sa.Column('legacy_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("publish_status IN ('draft', 'published', 'archived')", name='ck_people_publish_status'),
    sa.CheckConstraint("status IN ('faculty', 'current', 'alumni')", name='ck_people_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index('ix_people_graduation_year', ['graduation_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_slug'), ['slug'], unique=True)
        batch_op.create_index('ix_people_status_publish_sort', ['status', 'publish_status', 'sort_order'], unique=False)

    op.create_table('redirects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_path', sa.String(length=500), nullable=False),
    sa.Column('new_path', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('status_code IN (301, 302)', name='ck_redirects_status_code'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redirects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redirects_old_path'), ['old_path'], unique=True)

    op.create_table('research_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('output_type', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('title_zh', sa.Text(), nullable=True),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('summary_zh', sa.Text(), nullable=True),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('problem_zh', sa.Text(), nullable=True),
    sa.Column('problem_en', sa.Text(), nullable=True),
    sa.Column('method_zh', sa.Text(), nullable=True),
    sa.Column('method_en', sa.Text(), nullable=True),
    sa.Column('results_zh', sa.Text(), nullable=True),
    sa.Column('results_en', sa.Text(), nullable=True),
    sa.Column('significance_zh', sa.Text(), nullable=True),
    sa.Column('significance_en', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('dataset_url', sa.String(length=500), nullable=True),
    sa.Column('authors_display_text', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.Text(), nullable=True),
    sa.Column('hero_image_path', sa.String(length=255), nullable=True),
    sa.Column('hero_image_alt_zh', sa.String(length=220), nullable=True),
    sa.Column('hero_image_alt_en', sa.String(length=220), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('publish_status', sa.String(length=20), nullable=False),
    sa.Column('seo_title_zh', sa.String(length=180), nullable=True),
    sa.Column('seo_description_zh', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("output_type IN ('journal', 'conference', 'project', 'prototype', 'simulation', 'dataset', 'other')", name='ck_research_outputs_type'),
    sa.CheckConstraint("publish_status IN ('draft', 'published', 'archived')", name='ck_research_outputs_publish_status'),
    sa.CheckConstraint('year >= 1900 AND year <= 2200', name='ck_research_outputs_year_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_outputs', schema=None) as batch_op:
        batch_op.create_index('ix_research_featured', ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_outputs_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_outputs_slug'), ['slug'], unique=True)
        batch_op.create_index('ix_research_publish_year_type', ['publish_status', 'year', 'output_type'], unique=False)

    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_name_zh', sa.String(length=160), nullable=False),
    sa.Column('lab_name_en', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=80), nullable=True),
    sa.Column('department_zh', sa.String(length=160), nullable=True),
    sa.Column('department_en', sa.String(length=200), nullable=True),
    sa.Column('university_zh', sa.String(length=160), nullable=True),
    sa.Column('university_en', sa.String(length=200), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('hero_title_zh', sa.Text(), nullable=True),
    sa.Column('hero_title_en', sa.Text(), nullable=True),
    sa.Column('hero_intro_zh', sa.Text(), nullable=True),
    sa.Column('hero_intro_en', sa.Text(), nullable=True),
    sa.Column('hero_media_path', sa.String(length=255), nullable=True),
    sa.Column('hero_media_alt_zh', sa.String(length=220), nullable=True),
    sa.Column('research_focus_json', sa.Text(), nullable=True),
    sa.Column('lab_proof_json', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('address_zh', sa.Text(), nullable=True),
    sa.Column('address_en', sa.Text(), nullable=True),
    sa.Column('map_url', sa.String(length=500), nullable=True),
    sa.Column('join_title_zh', sa.String(length=200), nullable=True),
    sa.Column('join_body_zh', sa.Text(), nullable=True),
    sa.Column('join_cta_label_zh', sa.String(length=120), nullable=True),
    sa.Column('join_cta_url', sa.String(length=500), nullable=True),
    sa.Column('about_intro_zh', sa.Text(), nullable=True),
    sa.Column('about_methods_zh', sa.Text(), nullable=True),
    sa.Column('default_title_suffix', sa.String(length=120), nullable=True),
    sa.Column('default_description_zh', sa.String(length=320), nullable=True),
    sa.Column('og_image_path', sa.String(length=255), nullable=True),
    sa.Column('production_base_url', sa.String(length=255), nullable=True),
    sa.Column('official_ntust_url', sa.String(length=500), nullable=True),
    sa.Column('social_links_json', sa.Text(), nullable=True),
    sa.Column('llms_txt_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('create', 'update', 'publish', 'archive', 'login', 'login_failed', 'logout', 'password_change', 'graduate', 'delete')", name='ck_audit_logs_action'),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('research_output_people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_output_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('contributor_role', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("contributor_role IS NULL OR contributor_role IN ('author', 'student', 'supervisor', 'contributor')", name='ck_output_person_role'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_output_id'], ['research_outputs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_output_id', 'person_id', name='uq_output_person')
    )
    with op.batch_alter_table('research_output_people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_output_people_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_output_people_research_output_id'), ['research_output_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_output_people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_output_people_research_output_id'))
        batch_op.drop_index(batch_op.f('ix_research_output_people_person_id'))

    op.drop_table('research_output_people')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_admin_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('site_settings')
    with op.batch_alter_table('research_outputs', schema=None) as batch_op:
        batch_op.drop_index('ix_research_publish_year_type')
        batch_op.drop_index(batch_op.f('ix_research_outputs_slug'))
        batch_op.drop_index(batch_op.f('ix_research_outputs_doi'))
        batch_op.drop_index('ix_research_featured')

    op.drop_table('research_outputs')
    with op.batch_alter_table('redirects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redirects_old_path'))

    op.drop_table('redirects')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index('ix_people_status_publish_sort')
        batch_op.drop_index(batch_op.f('ix_people_slug'))
        batch_op.drop_index(batch_op.f('ix_people_legacy_id'))
        batch_op.drop_index('ix_people_graduation_year')

    op.drop_table('people')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
